name: Dependency Analysis

on:
  push:
    paths:
      - '**/*.java'
  pull_request:
    paths:
      - '**/*.java'

jobs:
  analyze-dependency:
    name: Analyze Method Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install javalang
        run: pip install javalang

      - name: Run Dependency Analyzer
        run: python dependency_analyzer.py

      - name: Upload Dependency Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-analysis-report
          path: dependency_report.html
